"""init schema

Revision ID: a06a50a7bb1b
Revises: 
Create Date: 2025-09-08 20:10:45.146270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06a50a7bb1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Enum('ON_MEMBER_JOIN', 'ON_MEMBER_LEAVE', 'ON_GUILD_JOIN', 'ON_GUILD_LEAVE', name='messagetype'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('title_url', sa.String(length=2048), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embed_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('inline', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embed_fields')
    op.drop_table('messages')
    op.drop_table('servers')
    # ### end Alembic commands ###
